{% set name = "google-cloud-containeranalysis" %}
{% set version = "2.0.0" %}
{% set sha256 = "528318f00f796361232c0681ae8284d2626b1d754a54d28cb64ad1e1d77f51f0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13.0dev
    - enum34
    - grafeas

test:
  imports:
    - grpc
    - grafeas.grafeas_v1
    - google.cloud.devtools
    - google.cloud.devtools.containeranalysis
    - google.cloud.devtools.containeranalysis_v1

about:
  home: https://github.com/googleapis/python-containeranalysis
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Container Analysis API client library
  description: "Google Cloud Container Analysis API client library is an implementation of the Grafeas API, which stores, and enables querying and retrieval of critical metadata about all of your software artifacts.\nSee the [quick start guide](https://googleapis.dev/python/containeranalysis/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/containeranalysis/latest/index.html
  dev_url: https://github.com/googleapis/python-containeranalysis

extra:
  recipe-maintainers:
    - parthea
